spring:
#  #静态资源处理
#  resources:
#    #启用默认静态资源处理，默认启用
#    add-mappings: true
#    cache:
#      cachecontrol:
#        #缓存响应时间，单位秒
#        max-age: 3600
#    chain:
#      #资源链中启用缓存，默认启用
#      cache: true
#      #启用资源链，默认禁用
#      enabled: true
#      #启用压缩资源(gzip,brotli)解析,默认禁用
#      compressed: true
#      #启用H5应用缓存，默认禁用
#      html-application-cache: true
#    #静态资源位置
#    static-locations: classpath:/static/
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: seckill
    username: root
    password: 1234
    # 使用springboot自带的hikari连接池
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 最大连接数,默认 10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # Redis配置
  redis:
    # 服务器地址
    host: 192.168.1.100
#    host: 175.178.110.18
    # 端口
    port: 6379
    # 密码
#    password: 6379
    # 默认操作的数据库
    database: 0
    # 超时时间
    connect-timeout: 10000ms
    # lettuce连接池
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 100
        # 最小空闲连接，默认0
        min-idle: 5

  # RabbitMQ配置
  rabbitmq:
    # 服务器地址
    host: 192.168.1.101
#    host: 175.178.110.18
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # AMQP端口：5672   HTTP端口：15672    clustering（集群）端口：25672
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间，默认1000ms，1秒
        initial-interval: 1000ms
        # 重试最大次数，默认3次
        max-attempts: 3
        # 重试最大间隔时间，默认10000ms，10秒
        max-interval: 10000ms
        # 重试的间隔乘数，比如multiplier: 2，第一次就等10s，第二次就等20s，第三次就等40s
        multiplier: 1

# Mybatis-Plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.simon.seckill.pojo

# MyBatis日志：SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.simon.seckill.mapper: debug
